export const IMAGE_SIZES = [
  {
    label: "Small (256 X 256)",
    value: "Small",
  },
  {
    label: "Medium (512 X 512)",
    value: "Medium",
  },
  {
    label: "Large (1024 X 1024)",
    value: "Large",
  },
];

export const promptList = [
  "A serene autumn landscape with a reflective lake surrounded by trees with colorful fall foliage, in the style of the Hudson River School, capturing the romantic essence and fine details.",
  "A lively marketplace in the 17th century Netherlands, with people bustling about, stalls with a variety of goods, and a warm atmosphere, inspired by Pieter Aertsen, using oil painting techniques.",
  "A surrealist painting that depicts a dreamlike scene with floating islands, bizarre creatures, and distorted perspectives, inspired by Salvador Dalí and Max Ernst, with intricate details and vibrant colors.",
  "A tranquil Zen garden with cherry blossom trees, a small bridge, and koi fish swimming in a pond.",
  "An abstract expressionist painting using bold brush strokes, dripping paint, and vibrant colors, reflecting the inner emotions and turmoil, inspired by the works of Jackson Pollock.",
  "A portrait of a mysterious woman sitting in an ornate, gothic throne room, with subtle elements of fantasy and magical realism, painted with the dark and dramatic style of the Baroque period.",
  "A dynamic action scene of a knight battling a dragon on a cliffside, with roaring waves below, inspired by the Romanticism movement, reminiscent of the works of Eugène Delacroix.",
  "A quaint Italian seaside village with colorful buildings, boats, and the reflection of the setting sun on the water, in the impressionist style of Claude Monet, with visible brush strokes and dappled light.",
  "A cubist painting of a still life with geometric shapes, fragmented forms, and multiple perspectives, inspired by the works of Pablo Picasso and Georges Braque, using a muted color palette.",
  "A futuristic cityscape with towering skyscrapers, flying vehicles, and a diverse population of humans and robots, painted in a concept art style inspired by Syd Mead, with a focus on detail and realism.",
  "A black and white street photography of a busy New York City intersection with the Empire State Building in the background, capturing the energy and chaos of city life.",
  "A majestic aerial view of the Great Barrier Reef, capturing the vibrant colors and patterns of the coral, with a focus on clarity and sharpness to show the delicate ecosystem, 12mm shot.",
  "A close-up macro shot of morning dew on a spider’s web, with the focus on the intricate patterns and water droplets, giving it an ethereal quality, high resolution.",
  "A powerful portrait of an elderly person, capturing the wrinkles, texture of the skin, and expressive eyes that tell a story of a lifetime, in high resolution and natural lighting.",
  "A realistic landscape shot of the Northern Lights dancing over a snowy mountain range in Iceland, with long exposure to capture the motion and vibrant colors.",
  "A vintage-style photograph of a classic car on Route 66, with a desert backdrop, taken with the effect of film photography and graininess for a nostalgic feel.",
  "An action shot of a professional ballet dancer mid-leap on a city rooftop at dusk, capturing the movement, grace, and urban environment in a dynamic composition.",
  "A candid shot of a crowded marketplace in Marrakesh, Morocco, capturing the colors, textures, and atmosphere of the place, with a shallow depth of field focusing on a street vendor.",
  "A panoramic view of a starry night sky in the Atacama Desert, Chile, capturing the Milky Way and other celestial bodies, with an emphasis on clarity and depth of field.",
  "A close-up shot of a raindrop about to fall from a leaf, with a focus on reflection and the vibrant greenery around it, creating a fresh and pure atmosphere.",
  "A futuristic cyberpunk cityscape at night with towering neon-lit skyscrapers, flying cars, and a diverse crowd of humans and androids, in a highly detailed digital painting reminiscent of Blade Runner.",
  "A vibrant and whimsical fantasy forest with magical creatures, glowing plants, and a flowing river, in a digital painting style inspired by video games like Ori and the Blind Forest.",
  "A character concept art of a steampunk inventor with mechanical limbs, wearing goggles and a leather trench coat, in a detailed digital painting with a focus on textures and materials.",
  "A digital painting of a space battle scene, with intricate spaceships, laser beams, and explosions, inspired by the epic scale and visual style of Star Wars.",
  "A serene underwater scene with a mermaid sitting on a rock, surrounded by colorful coral reefs and fish, in a digital art style with a focus on lighting and water effects.",
  "A haunting gothic horror scene of an abandoned mansion on a hill, with fog, full moon, and shadowy figures, in a digital painting style reminiscent of the Castlevania game series.",
  "A dynamic superhero action scene with characters flying, fighting, and using their powers, in a digital comic book style, with bold colors and dramatic angles.",
  "A mystical landscape of floating islands, ancient ruins, and magical artifacts, in a high-fantasy digital art style inspired by the environments in the game Final Fantasy.",
  "A portrait of a post-apocalyptic warrior with battle scars, armor, and weapons, standing in a desolate wasteland, in a detailed digital painting with gritty textures, inspired by the Mad Max franchise.",
  "A digital painting of a serene Japanese garden in autumn, with a tea house, koi pond, and maple trees with falling leaves, with an anime-inspired art style reminiscent of Studio Ghibli films.",
  "Portrait of a robot detective",
  "Portrait of a robot detective, holding a rose in his hand",
  "Portrait of a robot detective, in the style of Salvador Dali",
];
